import Header from './components/header/header';
import Footer from './components/footer/footer';
import './globals.css';
import './common.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id="modal-root">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
